### ISSUE TITLE
Height of indicator is too small if the tab list is long

### ISSUE THREAD

**Issue by haselwarter** [piroor/tst-active-tab-on-scrollbar#2]
First of all, thank you for your great work.

It seems that the height of the indicator is scaled inversely with the number of tabs in a tree. If that number is large, the height of the indicator diminishes to a point of being less visible. 
Adding a (possibly configurable) minimum height for the indicator would help.

**Comment by piroor** [comment]
Thanks, and sorry for my long silence. The commit 50443f6 should fix this.
